name: docker build

on: workflow_dispatch

env:
  USERNAME: maksimstojkovic
  PROJECT: dolibarr
  TAG: develop
  BUILD_PATH: images/develop/php7.3-apache
  PLATFORMS: linux/arm/v7,linux/arm64,linux/amd64

jobs:
  buildx:
    name: Build Multi-Platform Image and Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: 'multiarch-build-workflow'

      - name: Setup Docker Buildx
        run: |
          # Build docker buildx from source
          export DOCKER_BUILDKIT=1
          docker build --platform=local -o . git://github.com/docker/buildx
          mkdir -p ~/.docker/cli-plugins
          mv buildx ~/.docker/cli-plugins/docker-buildx

          # Docker version information
          echo "DOCKER VERSION:"
          docker info
          echo "BUILDX VERSION:"
          docker buildx version

          # Install qemu-user-static container
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name builder --driver docker-container --use
          docker buildx inspect --bootstrap

      - name: Build and Push
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          # Login
          echo "$DOCKER_TOKEN" | docker login -u "$USERNAME" --password-stdin

          # Setup build parameters
          BUILD_PARAMS="--platform="$PLATFORMS" --push"

          # Build image as tagged version
          docker buildx build -t "$USERNAME"/"$PROJECT":"$TAG" $BUILD_PARAMS "$BUILD_PATH"
          